### ISSUE TITLE
LogMessage.SourceType Capitalization

### ISSUE THREAD

**Issue by poy** [cloudfoundry/diego-cf-compatibility#2]
We noticed on our bosh lites (running DEAs) that the `source_type` from a `LogMessage` is `App`. However on a deployment with Diego, the same message has the `source_type` as `APP`.

Example:

DEA: `source_type:"App"`
Diego: `source_type:"APP"`

**Comment by emalm** [comment]
Yes, this is intentional, as all the other log source identifiers in the system use all-caps (STG, API, RTR, DEA, LGR). The smoke-tests already accommodate for this difference: https://github.com/cloudfoundry/cf-smoke-tests/blob/master/smoke/logging/loggregator_test.go#L58. I'll add something to https://github.com/cloudfoundry-incubator/diego-design-notes/blob/master/migrating-to-diego.md#diego-deltas about it.

Kudos for finding this repo, but this isn't really the right place to raise the issue. This repo is solely for recording which versions of CF and Diego are compatible, as determined by CATs runs on A1.

Thanks,
Eric

**Comment by poy** [comment]
I wasn't trying to indicate a bug, more just wondering if it needed to be documented as a migration. If not, no worries.

**Comment by emalm** [comment]
Thanks, @apoydence! I've finally had a chance to document the difference in https://github.com/cloudfoundry-incubator/diego-design-notes/blob/master/migrating-to-diego.md#application-log-lines, and I'll also get it into the CF docs soon.

Best,
Eric
